server:
  port: 0
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/xsneakers_auth
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
    fetch-registry: true
    register-with-eureka: true

token:
  access:
    secret:
    expiration: 300000  # 5 minutes
  refresh:
    secret:
    expiration: 604800000  # 7 days
